
import type { Job } from './types';

export const jobListings: Job[] = [
  {
    id: '1',
    dateTime: '2025-10-18T18:29:16.000Z',
    title: 'Data Scientist',
    description: 'Neural Surge is seeking a talented Data Scientist to join our innovative team. You will work on cutting-edge machine learning models.',
    location: 'Lahore, Punjab, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/data-scientist-at-neural-surge-4313863808',
  },
  {
    id: '2',
    dateTime: '2025-10-15T19:23:55.000Z',
    title: 'Data Scientist',
    description: 'Fusemachines is looking for a Data Scientist to help build and deploy AI solutions for our global clients. Strong Python skills required.',
    location: 'Islamabad, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/data-scientist-at-fusemachines-4315349226',
  },
  {
    id: '3',
    dateTime: '2025-10-15T00:00:00.000Z',
    title: 'Data Scientist (Remote Contract)',
    description: 'SME Careers is hiring a contract-based Data Scientist for a remote position. JOB ID: DataScience-25-118.',
    location: 'Remote (Pakistan)',
    applyLink: '',
  },
  {
    id: '4',
    dateTime: '2025-10-14T12:42:19.000Z',
    title: 'Data Scientist',
    description: 'Yakam Consulting is hiring a Data Scientist to analyze large datasets and drive business insights.',
    location: 'Lahore, Punjab, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/data-scientist-at-yakam-consulting-4311971343',
  },
  {
    id: '5',
    dateTime: '2025-10-10T12:58:54.000Z',
    title: 'Data Scientist / Developer',
    description: 'Gigalabs (Pvt) Ltd. is hiring a hybrid Data Scientist/Developer to build data-driven applications.',
    location: 'Lahore, Punjab, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/data-scientist-developer-at-gigalabs-pvt-ltd-4312813308',
  },
  {
    id: '6',
    dateTime: '2025-09-28T11:17:23.000Z',
    title: 'Data Scientist, Tech',
    description: 'ibex is hiring a Data Scientist in our tech division to work on predictive analytics and optimization projects.',
    location: 'Lahore, Punjab, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/data-scientist-tech-at-ibex-4233401031',
  },
  {
    id: '7',
    dateTime: '2025-08-15T10:35:41.000Z',
    title: 'Data Scientist',
    description: 'Fusemachines is hiring a Data Scientist to join their growing team in Islamabad.',
    location: 'Islamabad, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/data-scientist-at-fusemachines-4286658719',
  },
  {
    id: '8',
    dateTime: '2025-08-01T11:40:00.000Z',
    title: 'WhatsApp API Developer',
    description: 'Translation Empire PK is looking for a WhatsApp API Developer to integrate messaging solutions.',
    location: 'Rawalpindi, Punjab, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/whatsapp-api-developer-at-translation-empire-pk-4278796367',
  },
  {
    id: '9',
    dateTime: '2025-08-01T11:08:02.000Z',
    title: 'WhatsApp API Developer',
    description: 'Translation Empire PK is hiring a WhatsApp API Developer for our Islamabad office.',
    location: 'Islamabad, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/whatsapp-api-developer-at-translation-empire-pk-4278794046',
  },
  {
    id: '10',
    dateTime: '2025-07-29T10:31:22.000Z',
    title: 'Natural Language Processing (NLP) Engineer',
    description: 'Translation Empire PK has an opening for an NLP Engineer to work on language models and text processing pipelines.',
    location: 'Islamabad, Pakistan',
    applyLink: 'https://pk.linkedin.com/jobs/view/natural-language-processing-nlp-engineer-at-translation-empire-pk-4283431437',
  },
];
